version: '3.8'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=blog_admin_user
      - POSTGRES_PASSWORD=blog_admin_password
      - POSTGRES_DB=blog_site_database
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data/:/var/lib/postgresql/data
  blog_app:
    build: .
    container_name: blog_app
    ports:
      - 8002:8002
    image: blog_app:blog_app
    volumes:
      - .:/blog_app
    command: python manage.py runserver 0.0.0.0:8002
    depends_on:
      - db